debug: FALSE
project_name: MINT
project_sub_name: The BOS Manual Intervention Module
secret_key: THINK CLOCK SMOG FLAG SMACK TINKER FLUNK # enter any random string
advanced_features: True

sql_database: "sqlite:///{cwd}/bookied-local.db"

dataproxy_link:
    ping_interval_in_seconds: 300

    proxies:

connection:
    use: gladiator # enter your desired chain

    elizabeth:
        node:
          - ws://ec2-99-79-98-229.ca-central-1.compute.amazonaws.com:8090
        nobroadcast: False
        num_entries: 1

    hercules:
        node:
            - wss://hercules.peerplays.download/api
        nobroadcast: False
        num_entries: 1


    gladiator:
        node:
            - ws://96.46.49.15:8090
        nobroadcast: False
        num_entries: 1

allowed_assets:
    - BTFUN
    - PPY
    - TEST
    - BTF

