node: ws://ec2-99-79-98-229.ca-central-1.compute.amazonaws.com:8090
# node: wss://fred.peerplays.download/api
# node: wss://irona.peerplays.download/api
# node: wss://hercules.peerplays.download/api
# proposer: 'init0'
# proposal_expiration: 300
# password: peerplays**
bosApis: 
  - "http://35.183.41.242:8010/trigger"
chainName : "elizabeth"
