debug: FALSE
project_name: MINT
project_sub_name: The BOS Manual Intervention Module
secret_key: THINK CLOCK SMOG FLAG SMACK TINKER FLUNK # enter any random string
advanced_features: True

sql_database: "sqlite:///{cwd}/bookied-local.db"

dataproxy_link:
    ping_interval_in_seconds: 300

    proxies:

connection:
    use: beatrice # enter your desired chain

    beatrice:
        node:
          - ws://<API_NODE_HOST>:<API_NODE_PORT>
        nobroadcast: False
        num_entries: 1

allowed_assets:
    - BTFUN
    - PPY
    - TEST
    - BTF

potatoNames:
  - "couchpotato1"
  - "couchpotato2"

bosApis: 
  - "http://<BOS_AUTO_HOST1>:8010/trigger"
  - "http://<BOS_AUTO_HOST2>:8010/trigger"
